### ISSUE TITLE
Issue caused by this package when installing buffalo

### ISSUE THREAD

**Issue by wilsandbrink** [gobuffalo/release#11]
When trying to install buffalo I keep gettings this error: `# github.com/gobuffalo/release/genny/release
..\..\go\src\github.com\gobuffalo\release\genny\release\options.go:42:18: cannot use v (type *semver.Version) as type semver.Version in assignment`
and it seems to be caused by this package.

**Comment by markbates** [comment]
The `semver` package has changed, and broken their public API. If you could fill in the details of the issue form, that would help us track this down. If you're not using modules, can you turn them on and see if that fixes the issue? Again, without all the detail it's hard to help.

**Comment by wilsandbrink** [comment]
Ok now I'm getting a different error that doesn't seem to be related to the one I received before.
```
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in C:\Users\wilsa\go\pkg\mod\cache\vcs\83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
        fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Timed out
go get: error loading module requirements
```

And is the issue form you are referring to the one from the buffalo repo?

**Comment by wilsandbrink** [comment]
Oh https://github.com/tektoncd/cli/issues/259

**Comment by wilsandbrink** [comment]
Ok this issue doesn't seem to be caused by anything buffalo related anymore.

**Comment by wilsandbrink** [comment]
I read https://github.com/gobuffalo/buffalo/issues/1781 and then proceeded to upgrade my go version to 1.13 which fixed the issue.
